CREATE TABLE IF NOT EXISTS despesas (
    id SERIAL PRIMARY KEY NOT NULL,
    valor DECIMAL(10,2) NOT NULL,
    data DATE,
    descricao TEXT NOT NULL,
    usuario INTEGER NOT NULL,
    CONSTRAINT fk_usuario FOREIGN KEY (usuario) REFERENCES users(id) ON DELETE CASCADE
);